/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logica.Conversor;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author NS
 */
public final class JPanelDecodificar extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCodificar
     */
    private Conversor gestorBase64;
    private File fileselect = null;
    private String contenido = "";

    public JPanelDecodificar(Conversor object) {
        initComponents();
        setSize(new java.awt.Dimension(530, 310));
        gestorBase64 = object;
        jButton1.setVisible(false);
        bloquearBoton();
        jLabelSolicitud.setIcon(null);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelArchivoActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonDecodificar = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jLabelSolicitud = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(530, 310));

        jLabel1.setText("Archivo :");

        jPanel1.setLayout(new java.awt.GridLayout());

        jButtonDecodificar.setText("Decodificar");
        jButtonDecodificar.setMinimumSize(new java.awt.Dimension(220, 23));
        jButtonDecodificar.setPreferredSize(new java.awt.Dimension(220, 23));
        jButtonDecodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecodificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDecodificar);

        jButtonSeleccionar.setText("Seleccionar json");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeleccionar);

        jLabelSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Aceptar.png"))); // NOI18N

        jButton1.setText("X");
        jButton1.setToolTipText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabelSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelArchivoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelArchivoActual, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();
        selector.setDialogType(JFileChooser.SAVE_DIALOG);
        selector.setFileFilter(new FileNameExtensionFilter("json", "json"));

        int showDialog = selector.showDialog(this, "Importar JSON");
        if (showDialog == JFileChooser.APPROVE_OPTION) {

            try {
                JSONParser cont = new JSONParser();
                JSONObject configuracion;

                configuracion = (JSONObject) cont.parse(new FileReader(selector.getSelectedFile().getAbsolutePath()));
                String archivo = (String) configuracion.get("archivo");
                String contenido = (String) configuracion.get("contenido");
                jLabelArchivoActual.setText(archivo);
                this.contenido = contenido;

                bloquearBoton();
                jButtonSeleccionar.setEnabled(false);
                jButton1.setVisible(true);

            } catch (IOException | ParseException ex) {
                JOptionPane.showMessageDialog(this, "Error\n" + ex.getMessage());
                aprobacionVisual(false);
            }

        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonDecodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecodificarActionPerformed
        // TODO add your handling code here:
        try{
        aprobacionVisual(gestorBase64.decodificarBase64(contenido, jLabelArchivoActual.getText()));
        }catch(IllegalArgumentException | IOException ex){
            JOptionPane.showMessageDialog(this,"No se pudo decodificar el archivo\n"+ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDecodificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabelArchivoActual.setText("");
        jButton1.setVisible(false);
        jButtonSeleccionar.setEnabled(true);
        bloquearBoton();
        jLabelSolicitud.setIcon(null);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    public void bloquearBoton() {
        if (jButtonDecodificar.isEnabled()) {
            jButtonDecodificar.setEnabled(false);
        } else {
            jButtonDecodificar.setEnabled(true);
        }
    }

    public void aprobacionVisual(boolean accion) {

        if (accion) {

            jLabelSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Aceptar.png")));

        } else {
            jLabelSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Cancelar.png")));

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDecodificar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelArchivoActual;
    private javax.swing.JLabel jLabelSolicitud;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
