/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prosimulacionfinalsolovista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Corrida;
import logica.generadorMixto.Generador;
import logica.generadorMixto.Respuesta;

/**
 *
 * @author NS
 */
public class tablaCorridas extends javax.swing.JFrame {

    /**
     * Creates new form tablaCorridas
     */
    private int posicionSimulacion;
    private Respuesta datosGenerados;
    private ArrayList<Corrida> listaCorridas;

    public tablaCorridas() {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("ProSimulación 2017-1");
        posicionSimulacion = 0;
        listaCorridas = new ArrayList<>();
        iniciarSimulacionDatos.start();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                        "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorridas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonAnimarSeleccion = new javax.swing.JButton();
        jButtonDatosRelevantesSeleccionados = new javax.swing.JButton();
        jButtonDatosGenerales = new javax.swing.JButton();
        BotonAnálisis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTableCorridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm", "Núm. Personas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCorridas);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones sobre la corrida"));

        jButtonAnimarSeleccion.setText("Animar");
        jButtonAnimarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimarSeleccionActionPerformed(evt);
            }
        });

        jButtonDatosRelevantesSeleccionados.setText("Datos relevantes");
        jButtonDatosRelevantesSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosRelevantesSeleccionadosActionPerformed(evt);
            }
        });

        jButtonDatosGenerales.setText("Datos generados");
        jButtonDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosGeneralesActionPerformed(evt);
            }
        });

        BotonAnálisis.setText("Análisis");
        BotonAnálisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnálisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAnálisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnimarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDatosRelevantesSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnimarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDatosRelevantesSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonAnálisis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones sobre todas las corridas"));

        jButton4.setText("Estadística ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Análisis ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/UDeC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnimarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimarSeleccionActionPerformed

        if (jTableCorridas.getSelectedRow() >= 0 || 150 < jTableCorridas.getSelectedRow()) {

            vistaCafeteria2 vista = new vistaCafeteria2(null, true, listaCorridas.get(jTableCorridas.getSelectedRow()), jTableCorridas.getSelectedRow());

            vista.setVisible(true);

        }


    }//GEN-LAST:event_jButtonAnimarSeleccionActionPerformed

    private void jButtonDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosGeneralesActionPerformed
        // TODO add your handling code here:
        if (jTableCorridas.getSelectedRow() >= 0 || 150 < jTableCorridas.getSelectedRow()) {

            tablaDatos vista = new tablaDatos(this, true, listaCorridas.get(jTableCorridas.getSelectedRow()), jTableCorridas.getSelectedRow());

            vista.setVisible(true);

        }

    }//GEN-LAST:event_jButtonDatosGeneralesActionPerformed

    private void jButtonDatosRelevantesSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosRelevantesSeleccionadosActionPerformed
        // TODO add your handling code here:

        if (jTableCorridas.getSelectedRow() >= 0 || 150 < jTableCorridas.getSelectedRow()) {

            ArrayList<Corrida> lista = new ArrayList<>();
            lista.add(listaCorridas.get(jTableCorridas.getSelectedRow()));
            InformacionRelevante vista = new InformacionRelevante(null, true, lista, jTableCorridas.getSelectedRow() + "");

            vista.setVisible(true);

        }

    }//GEN-LAST:event_jButtonDatosRelevantesSeleccionadosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        InformacionRelevante vista = new InformacionRelevante(null, true, listaCorridas, "Análisis general");

        vista.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        vistaBayes a = new vistaBayes(listaCorridas);
        a.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void BotonAnálisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnálisisActionPerformed
        // TODO add your handling code here:

        if (jTableCorridas.getSelectedRow() >= 0 || 150 < jTableCorridas.getSelectedRow()) {
            ArrayList<Corrida> lista = new ArrayList<>();
            lista.add(listaCorridas.get(jTableCorridas.getSelectedRow()));
            vistaBayes vista = new vistaBayes(lista);

            vista.setVisible(true);

        }

    }//GEN-LAST:event_BotonAnálisisActionPerformed

    Thread iniciarSimulacionDatos = new Thread() {
        @Override
        public void run() {

            datosGenerados = Generador.congruencialMixto(19, 300, 13, 53693);

            for (int i = 0; i < 150; i++) {
                posicionSimulacion += 250;
                System.out.println("Núm Utilizado" + posicionSimulacion);
                listaCorridas.add(crearClientes(posicionSimulacion));
            }

            llenarTabla();

        }

    };

    public boolean llenarTabla() {

        DefaultTableModel model = (DefaultTableModel) jTableCorridas.getModel();
        for (; model.getRowCount() > 0;) {
            model.removeRow(0);
        }

        for (int i = 0; i < listaCorridas.size(); i++) {

            Integer[] datos = {i, listaCorridas.get(i).getClientes().size()};
            model.addRow(datos);

        }

        return true;

    }

    public Corrida crearClientes(int crear) {

        Corrida nueva = new Corrida();
        ArrayList<Double> numeros = new ArrayList<>();

        for (int i = posicionSimulacion; i < datosGenerados.size(); i++) {

            numeros.add(datosGenerados.get(i)[1]);

        }
        // posición del último número utilizado

        nueva.crearCorrida(numeros);

        return nueva;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnálisis;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAnimarSeleccion;
    private javax.swing.JButton jButtonDatosGenerales;
    private javax.swing.JButton jButtonDatosRelevantesSeleccionados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorridas;
    // End of variables declaration//GEN-END:variables
}
