/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prosimulacionfinalsolovista;

import static java.awt.image.ImageObserver.ERROR;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import logica.Cliente;
import logica.Corrida;
import logica.generadorMixto.Generador;
import logica.generadorMixto.Respuesta;

/**
 *
 * @author NS
 */
public final class vistaCafeteria2 extends javax.swing.JDialog {

    /**
     * Creates new form NewJFrame
     */
    private final ArrayList<JLabel> colaEsperaIconos;
    private final ArrayList<JLabel> colaServicioIconos;
    private ArrayList<JLabel> mesasLabel;
    private ArrayList<Boolean> ocupacionMesas;

    Corrida listaClienteCorridaActual;

    private int factorAceleracion;
    private double hora;

    ArrayList<Corrida> corridas;


    int posicionSimulacion;
    private int contPersonas = 0;
    boolean pruebas = true;
    boolean animancionON = true;
    private int numCorrida;

    public vistaCafeteria2(java.awt.Frame parent, boolean modal,Corrida datosGeneradosNumeros,int num) {
        
         super(parent, modal);
         numCorrida = num;
        
        initComponents();
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                     animancionON=false;
                     contPersonas = listaClienteCorridaActual.getClientes().size();
                  
                    }
                });
        
        
        
        colaEsperaIconos = new ArrayList<>();
        colaServicioIconos = new ArrayList<>();
        mesasLabel = new ArrayList<>();
        ocupacionMesas = new ArrayList<>();
        corridas = new ArrayList<>();
        
        listaClienteCorridaActual = datosGeneradosNumeros;

        posicionSimulacion = 0;
        factorAceleracion = 10;

        agregarLabel();

        setLocationRelativeTo(null);

        mesas.start();
        insertarPersona.start();
//        hiloSacarCola.start();
//        hiloSacarServicio.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanelOfinia = new javax.swing.JPanel();
        jLabelPC = new javax.swing.JLabel();
        Estante1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCaferiaMesas = new javax.swing.JPanel();
        jLabelMesa4 = new javax.swing.JLabel();
        jLabelMesa10 = new javax.swing.JLabel();
        jLabelMesa1 = new javax.swing.JLabel();
        jLabelMesa12 = new javax.swing.JLabel();
        jLabelMesa5 = new javax.swing.JLabel();
        jLabelMesa6 = new javax.swing.JLabel();
        jLabelMesa8 = new javax.swing.JLabel();
        jLabelMesa2 = new javax.swing.JLabel();
        jLabelMesa3 = new javax.swing.JLabel();
        jLabelMesa7 = new javax.swing.JLabel();
        jLabelMesa13 = new javax.swing.JLabel();
        jLabelMesa14 = new javax.swing.JLabel();
        jLabelMesa15 = new javax.swing.JLabel();
        jPanelColaServicio = new javax.swing.JPanel();
        jLabelPersonaServicio5 = new javax.swing.JLabel();
        jLabelPersonaServicio6 = new javax.swing.JLabel();
        jLabelPersonaServicio13 = new javax.swing.JLabel();
        jLabelPersonaServicio3 = new javax.swing.JLabel();
        jLabelPersonaServicio7 = new javax.swing.JLabel();
        jLabelPersonaServicio11 = new javax.swing.JLabel();
        jLabelPersonaServicio10 = new javax.swing.JLabel();
        jLabelPersonaServicio12 = new javax.swing.JLabel();
        jLabelPersonaServicio1 = new javax.swing.JLabel();
        jLabelPersonaServicio8 = new javax.swing.JLabel();
        jLabelPersonaServicio4 = new javax.swing.JLabel();
        jLabelPersonaServicio2 = new javax.swing.JLabel();
        jLabelPersonaServicio9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPersonaServicio14 = new javax.swing.JLabel();
        jLabelPersonaServicio15 = new javax.swing.JLabel();
        jLabelPersonaServicio16 = new javax.swing.JLabel();
        jLabelPersonaServicio17 = new javax.swing.JLabel();
        jLabelPersonaServicio18 = new javax.swing.JLabel();
        jLabelPersonaServicio19 = new javax.swing.JLabel();
        jPanelPasarela = new javax.swing.JPanel();
        jLabelPasarelaDerecha = new javax.swing.JLabel();
        jLabelPasarelaIzquierda = new javax.swing.JLabel();
        jLabelPersonaCola7 = new javax.swing.JLabel();
        jLabelPersonaCola3 = new javax.swing.JLabel();
        jLabelPersonaCola4 = new javax.swing.JLabel();
        jLabelPersonaCola6 = new javax.swing.JLabel();
        jLabelPersonaCola5 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabelPersonaCola2 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabelPersonaCola1 = new javax.swing.JLabel();
        jLabelPersonaCola8 = new javax.swing.JLabel();
        jLabelPersonaCola9 = new javax.swing.JLabel();
        jLabelPersonaCola10 = new javax.swing.JLabel();
        jLabelPersonaCola11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMesa11 = new javax.swing.JLabel();
        jLabelMesa9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCantidadPersonas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSliderVelocidad = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setTitle("Animación");
        setResizable(false);

        jLabelPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/vendedor.png"))); // NOI18N

        Estante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Estante.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/estantee.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanelOfiniaLayout = new javax.swing.GroupLayout(jPanelOfinia);
        jPanelOfinia.setLayout(jPanelOfiniaLayout);
        jPanelOfiniaLayout.setHorizontalGroup(
            jPanelOfiniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfiniaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelOfiniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOfiniaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Estante1)
                        .addGap(44, 44, 44))
                    .addGroup(jPanelOfiniaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabelPC)
                .addContainerGap())
        );
        jPanelOfiniaLayout.setVerticalGroup(
            jPanelOfiniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOfiniaLayout.createSequentialGroup()
                .addGroup(jPanelOfiniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOfiniaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelOfiniaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addComponent(Estante1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabelMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCaferiaMesasLayout = new javax.swing.GroupLayout(jPanelCaferiaMesas);
        jPanelCaferiaMesas.setLayout(jPanelCaferiaMesasLayout);
        jPanelCaferiaMesasLayout.setHorizontalGroup(
            jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                        .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMesa15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMesa2)
                                .addGap(29, 29, 29))
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabelMesa3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jLabelMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))))
                    .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                        .addComponent(jLabelMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addComponent(jLabelMesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabelMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addComponent(jLabelMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jLabelMesa14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCaferiaMesasLayout.setVerticalGroup(
            jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                        .addComponent(jLabelMesa14)
                        .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMesa8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                        .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addComponent(jLabelMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCaferiaMesasLayout.createSequentialGroup()
                                .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMesa15)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCaferiaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMesa6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel6.setText("SERVICIO");

        javax.swing.GroupLayout jPanelColaServicioLayout = new javax.swing.GroupLayout(jPanelColaServicio);
        jPanelColaServicio.setLayout(jPanelColaServicioLayout);
        jPanelColaServicioLayout.setHorizontalGroup(
            jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaServicioLayout.createSequentialGroup()
                        .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                                .addComponent(jLabelPersonaServicio6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPersonaServicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPersonaServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                                .addComponent(jLabelPersonaServicio14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelPersonaServicio15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPersonaServicio16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                                        .addComponent(jLabelPersonaServicio11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPersonaServicio12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPersonaServicio13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                                        .addComponent(jLabelPersonaServicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPersonaServicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPersonaServicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelPersonaServicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaServicioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaServicioLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(146, 146, 146))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaServicioLayout.createSequentialGroup()
                                        .addComponent(jLabelPersonaServicio17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabelPersonaServicio19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPersonaServicio18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))))))
                    .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelPersonaServicio8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPersonaServicio9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPersonaServicio10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelColaServicioLayout.setVerticalGroup(
            jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaServicioLayout.createSequentialGroup()
                        .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPersonaServicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPersonaServicio9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaServicio10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelPersonaServicio11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaServicio12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelPersonaServicio13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelColaServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersonaServicio14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaServicio15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaServicio17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaServicio18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaServicio16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPersonaServicio19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabelPasarelaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Barranda.png"))); // NOI18N

        jLabelPasarelaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Barranda.png"))); // NOI18N

        jLabelPersonaCola11.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanelPasarelaLayout = new javax.swing.GroupLayout(jPanelPasarela);
        jPanelPasarela.setLayout(jPanelPasarelaLayout);
        jPanelPasarelaLayout.setHorizontalGroup(
            jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasarelaLayout.createSequentialGroup()
                .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPasarelaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPersonaCola8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPersonaCola1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPersonaCola7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPersonaCola9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasarelaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPersonaCola11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPersonaCola10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                        .addComponent(jLabelPasarelaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasarelaLayout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        jPanelPasarelaLayout.setVerticalGroup(
            jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelPasarelaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelPasarelaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanelPasarelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPersonaCola1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPersonaCola2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPersonaCola5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPersonaCola11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPasarelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasarelaLayout.createSequentialGroup()
                    .addContainerGap(451, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        jLabelMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        jLabelMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabelMesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMesa11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelMesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información rápida"));

        jLabel1.setText("Minutos: ");

        jLabel2.setText("Llegadas");

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Velocidad");

        jSliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVelocidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(jLabelCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jSliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Opciones");
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Datos generales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator6);

        jMenuItem1.setText("Datos relevantes día");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOfinia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelColaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelCaferiaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanelPasarela, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOfinia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPasarela, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelColaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCaferiaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        tablaDatos tablita = new tablaDatos(null, true, listaClienteCorridaActual,numCorrida);
        tablita.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jSliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVelocidadStateChanged
        // TODO add your handling code here:

        jSliderVelocidad.setToolTipText("" + jSliderVelocidad.getValue());

            if (jSliderVelocidad.getValue() >= 0 && 10 < jSliderVelocidad.getValue()) {

            factorAceleracion = 860;
        }
        
        if (jSliderVelocidad.getValue() >= 10 && 25 < jSliderVelocidad.getValue()) {

            factorAceleracion = 560;
        }
        if (jSliderVelocidad.getValue() >= 25 && 50 < jSliderVelocidad.getValue()) {

            factorAceleracion = 150;
        }
        if (jSliderVelocidad.getValue() >= 50 && 75 < jSliderVelocidad.getValue()) {

            factorAceleracion = 20;
        }
        if (jSliderVelocidad.getValue() >= 75 && 100 < jSliderVelocidad.getValue()) {

            factorAceleracion = 10;
        }

    }//GEN-LAST:event_jSliderVelocidadStateChanged

    private void limpiarAnimacion() {

        jLabelPersonaCola1.setIcon(null);
        jLabelPersonaCola2.setIcon(null);
        jLabelPersonaCola3.setIcon(null);
        jLabelPersonaCola4.setIcon(null);
        jLabelPersonaCola5.setIcon(null);
        jLabelPersonaCola6.setIcon(null);
        jLabelPersonaCola7.setIcon(null);
        jLabelPersonaCola8.setIcon(null);
        jLabelPersonaCola9.setIcon(null);
        jLabelPersonaCola10.setIcon(null);
        jLabelPersonaCola11.setIcon(null);

        jLabelPersonaServicio1.setIcon(null);

        jLabelPersonaServicio2.setIcon(null);
        jLabelPersonaServicio3.setIcon(null);
        jLabelPersonaServicio4.setIcon(null);
        jLabelPersonaServicio5.setIcon(null);
        jLabelPersonaServicio6.setIcon(null);
        jLabelPersonaServicio7.setIcon(null);
        jLabelPersonaServicio8.setIcon(null);
        jLabelPersonaServicio9.setIcon(null);
        jLabelPersonaServicio10.setIcon(null);
        jLabelPersonaServicio11.setIcon(null);
        jLabelPersonaServicio12.setIcon(null);
        jLabelPersonaServicio13.setIcon(null);
        jLabelPersonaServicio14.setIcon(null);
        jLabelPersonaServicio15.setIcon(null);
        jLabelPersonaServicio16.setIcon(null);
        jLabelPersonaServicio17.setIcon(null);
        jLabelPersonaServicio18.setIcon(null);
        jLabelPersonaServicio19.setIcon(null);

        hora = 0;
        contPersonas = 0;

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        animancionON = false;


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           ArrayList<Corrida>  lista = new ArrayList<>();
            lista.add(listaClienteCorridaActual);
        
            InformacionRelevante vista = new InformacionRelevante(null, true, lista,  numCorrida+"");

            vista.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void establecerHora() {

        double b = (hora%60);
        
  

        jLabelHora.setText(""+(int)(hora/60)+" : "+(int)b);

    }

    public void cantidad(int cantidad) {

        jLabelCantidadPersonas.setText("" + cantidad);
    }

    public boolean agregarLabel() {

        colaEsperaIconos.clear();
        colaServicioIconos.clear();

        jLabelPersonaCola1.setIcon(null);
        jLabelPersonaCola2.setIcon(null);
        jLabelPersonaCola3.setIcon(null);
        jLabelPersonaCola4.setIcon(null);
        jLabelPersonaCola5.setIcon(null);
        jLabelPersonaCola6.setIcon(null);
        jLabelPersonaCola7.setIcon(null);
        jLabelPersonaCola8.setIcon(null);
        jLabelPersonaCola9.setIcon(null);
        jLabelPersonaCola10.setIcon(null);
        jLabelPersonaCola11.setIcon(null);

        jLabelPersonaServicio1.setIcon(null);

        jLabelPersonaServicio2.setIcon(null);
        jLabelPersonaServicio3.setIcon(null);
        jLabelPersonaServicio4.setIcon(null);
        jLabelPersonaServicio5.setIcon(null);
        jLabelPersonaServicio6.setIcon(null);
        jLabelPersonaServicio7.setIcon(null);
        jLabelPersonaServicio8.setIcon(null);
        jLabelPersonaServicio9.setIcon(null);
        jLabelPersonaServicio10.setIcon(null);
        jLabelPersonaServicio11.setIcon(null);
        jLabelPersonaServicio12.setIcon(null);
        jLabelPersonaServicio13.setIcon(null);
        jLabelPersonaServicio14.setIcon(null);
        jLabelPersonaServicio15.setIcon(null);
        jLabelPersonaServicio16.setIcon(null);
        jLabelPersonaServicio17.setIcon(null);
        jLabelPersonaServicio18.setIcon(null);
        jLabelPersonaServicio19.setIcon(null);

        // La Cola de espera
        colaEsperaIconos.add(jLabelPersonaCola1);
        colaEsperaIconos.add(jLabelPersonaCola2);
        colaEsperaIconos.add(jLabelPersonaCola3);
        colaEsperaIconos.add(jLabelPersonaCola4);
        colaEsperaIconos.add(jLabelPersonaCola5);
        colaEsperaIconos.add(jLabelPersonaCola6);
        colaEsperaIconos.add(jLabelPersonaCola7);
        colaEsperaIconos.add(jLabelPersonaCola8);
        colaEsperaIconos.add(jLabelPersonaCola9);
        colaEsperaIconos.add(jLabelPersonaCola10);
        colaEsperaIconos.add(jLabelPersonaCola11);

        // Cola se servicio 
        colaServicioIconos.add(jLabelPersonaServicio1);
        colaServicioIconos.add(jLabelPersonaServicio2);
        colaServicioIconos.add(jLabelPersonaServicio3);
        colaServicioIconos.add(jLabelPersonaServicio4);
        colaServicioIconos.add(jLabelPersonaServicio5);
        colaServicioIconos.add(jLabelPersonaServicio6);
        colaServicioIconos.add(jLabelPersonaServicio7);
        colaServicioIconos.add(jLabelPersonaServicio8);
        colaServicioIconos.add(jLabelPersonaServicio9);
        colaServicioIconos.add(jLabelPersonaServicio10);
        colaServicioIconos.add(jLabelPersonaServicio11);
        colaServicioIconos.add(jLabelPersonaServicio12);
        colaServicioIconos.add(jLabelPersonaServicio13);
        colaServicioIconos.add(jLabelPersonaServicio14);
        colaServicioIconos.add(jLabelPersonaServicio15);
        colaServicioIconos.add(jLabelPersonaServicio16);
        colaServicioIconos.add(jLabelPersonaServicio17);
        colaServicioIconos.add(jLabelPersonaServicio18);
        colaServicioIconos.add(jLabelPersonaServicio19);

        mesasLabel.add(jLabelMesa1);
        mesasLabel.add(jLabelMesa2);
        mesasLabel.add(jLabelMesa3);
        mesasLabel.add(jLabelMesa4);
        mesasLabel.add(jLabelMesa5);
        mesasLabel.add(jLabelMesa6);
        mesasLabel.add(jLabelMesa7);
        mesasLabel.add(jLabelMesa8);

        mesasLabel.add(jLabelMesa10);
        mesasLabel.add(jLabelMesa11);
        mesasLabel.add(jLabelMesa12);
        mesasLabel.add(jLabelMesa13);
        mesasLabel.add(jLabelMesa14);
        mesasLabel.add(jLabelMesa15);
        mesasLabel.add(jLabelMesa9);

        for (int i = 0; i <= 14; i++) {

            ocupacionMesas.add(false);

        }

        return true;

    }

    /**
     * @param sexo , true para Hombre y false para Mujer
     * @param rangoEdad, 0 para indicar que es joven,1 para adulto , 2 para
     * Adulto mayor
     */
    public boolean InsertarColaIcon(boolean sexo, int rangoEdad) {

        if (sexo == true) {

            switch (rangoEdad) {
                case 0: {
                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/HombreJoven.png")));
                        break;
                    }
                }
                case 1: {

                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/HombreAdulto.png")));

                        break;
                    }
                }
                case 2: {
                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/HombreAMayor.png")));
                        break;
                    }
                }

            }

        } else {
            switch (rangoEdad) {
                case 0: {
                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MujerJoven.png")));
                        break;
                    }
                }
                case 1: {

                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MujerAdulta.png")));

                        break;
                    }
                }
                case 2: {
                    int puesto = disponibilidad(false);
                    if (puesto != -1) {
                        colaEsperaIconos.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MujerAMayor.png")));
                        break;
                    }
                }

            }

        }

        return true;
    }

    /**
     * @param colaTipo ,true para cola de servicio y false para cola de espera
     * @return el número dónde se va a ubicar a la persona pero devuelve -1 sino
     * hay espacio
     */
    public int disponibilidad(boolean colaTipo) {

        if (colaTipo == true) {
            for (int i = 0; i < colaServicioIconos.size(); i++) {
                // Los JLabel que no estén visibles son los que están disponibles
                if (colaServicioIconos.get(i).getIcon() == null) {

                    return i;

                }
            }

        } else {
            for (int i = 0; i < colaEsperaIconos.size(); i++) {
                // Los JLabel que no estén visibles son los que están disponibles
                if (colaEsperaIconos.get(i).getIcon() == null) {

                    return i;

                }

            }

        }

        return -1;
    }

    public boolean sacarDeCola(boolean colaTipo) {

        ImageIcon moverCola;
        ImageIcon sacandoServicio;

        if (colaTipo) {

            if (!colaServicioIconos.isEmpty()) {
                sacandoServicio = (ImageIcon) colaEsperaIconos.get(0).getIcon();

                for (int i = 0; i < colaServicioIconos.size() - 1; i++) {
                    colaServicioIconos.get(i).setIcon(colaServicioIconos.get(i + 1).getIcon());

                }
                colaServicioIconos.get(colaServicioIconos.size() - 1).setIcon(null);

            }

        } else if (!colaEsperaIconos.isEmpty()) {
            moverCola = (ImageIcon) colaEsperaIconos.get(0).getIcon();

            for (int i = 0; i < colaEsperaIconos.size() - 1; i++) {
                colaEsperaIconos.get(i).setIcon(colaEsperaIconos.get(i + 1).getIcon());

            }
            colaEsperaIconos.get(colaEsperaIconos.size() - 1).setIcon(null);

            int disponibilidad = disponibilidad(true);
            if (disponibilidad != -1) {
                colaServicioIconos.get(disponibilidad).setIcon(moverCola);
            } else {
                insertarPersona.suspend();
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(vistaCafeteria2.class.getName()).log(Level.SEVERE, null, ex);
                }
                insertarPersona.resume();
            }

        }

        return true;

    }

    // Sección de animaciones
    //Permite darle "dinamica" a las personas de las mesas.
    Thread mesas = new Thread() {
        @Override
        public void run() {

            Random generador = new Random();
            while (animancionON) {
                try {
                    int puesto = generador.nextInt(15);

                    if (puesto >= 0 && puesto <= 14) {

                        Boolean estadoMesa = ocupacionMesas.get(puesto);

                        // True si tiene gente
                        if (estadoMesa) {

                            mesasLabel.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT1.png")));

                        } else {
                            mesasLabel.get(puesto).setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/MesaT2.png")));

                        }
                        ocupacionMesas.set(puesto, !estadoMesa);

                    }

                    Thread.sleep(1000 * generador.nextInt(15));
                } catch (InterruptedException ex) {
                    Logger.getLogger(vistaCafeteria2.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }

    };

    Thread insertarPersona = new Thread() {
        @Override
        public void run() {



            boolean bandera = true;
            int tamano = listaClienteCorridaActual.getClientes().size();

            while (animancionON && contPersonas < tamano) {

                try {

                    Cliente clientico = listaClienteCorridaActual.getClientes().get(contPersonas++);

                    hora += clientico.getTiempoLlegada();

                    establecerHora();

                    cantidad(contPersonas);

                    Thread.sleep(factorAceleracion * clientico.getTiempoLlegada());
                    System.out.println("Velocidad entrada " + (factorAceleracion * clientico.getTiempoLlegada()));
                    switch (clientico.getTipo()) {
                        case "joven": {
                            InsertarColaIcon(clientico.getGenero().equals("Hombre"), 0);
                            break;
                        }
                        case "Adulto": {
                            InsertarColaIcon(clientico.getGenero().equals("Hombre"), 1);
                            break;
                        }
                        case "Adulto mayor": {
                            InsertarColaIcon(clientico.getGenero().equals("Hombre"), 2);
                            break;
                        }

                    }

                    if (jLabelPersonaServicio19.getIcon() != null) {

                        Thread.sleep(1000 * 2);
                    }

                } catch (InterruptedException ex) {
                    Logger.getLogger(vistaCafeteria2.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (bandera) {
                    hiloSacarCola.start();
                    bandera = false;
                }
            }

        }

    };

    Thread hiloSacarCola = new Thread() {
        @Override
        public void run() {

            int tamano = listaClienteCorridaActual.getClientes().size();
            int cont = 0;
            boolean bandera = true;

            int caja = 1;

            while (animancionON) {

                try {

                    Cliente clientico = listaClienteCorridaActual.getClientes().get(cont);

                    if (clientico.getTiempoServicio() < 55) {
                        caja = (int) (clientico.getTiempoServicio() * 0.5);
                    }
                    if (clientico.getTiempoServicio() < 90 && clientico.getTiempoServicio() >= 55) {
                        caja = (int) (clientico.getTiempoServicio() * 0.55);
                    } else {
                        caja = (int) (clientico.getTiempoServicio() * 0.45);
                    }
                    Thread.sleep(factorAceleracion * caja);

                    sacarDeCola(false);

                } catch (InterruptedException ex) {
                    Logger.getLogger(vistaCafeteria2.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (bandera) {

                    hiloSacarServicio.start();
                    bandera = false;
                }

            }

        }

    };

    Thread hiloSacarServicio = new Thread() {
        @Override
        public void run() {

            int tamano = listaClienteCorridaActual.getClientes().size();
            int cont = 0;

            int servicio = 1;

            while (animancionON) {

                try {

                    Cliente clientico = listaClienteCorridaActual.getClientes().get(cont);

                    if (clientico.getTiempoServicio() < 55) {
                        servicio = (int) (clientico.getTiempoServicio() * 0.4);
                    }
                    if (clientico.getTiempoServicio() < 90 && clientico.getTiempoServicio() >= 55) {
                        servicio = (int) (clientico.getTiempoServicio() * 0.45);
                    } else {
                        servicio = (int) (clientico.getTiempoServicio() * 0.55);
                    }

                    Thread.sleep(factorAceleracion * servicio);
                    sacarDeCola(true);

                } catch (InterruptedException ex) {
                    Logger.getLogger(vistaCafeteria2.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            //   animancionON = false;

        }

    };




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estante1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCantidadPersonas;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelMesa1;
    private javax.swing.JLabel jLabelMesa10;
    private javax.swing.JLabel jLabelMesa11;
    private javax.swing.JLabel jLabelMesa12;
    private javax.swing.JLabel jLabelMesa13;
    private javax.swing.JLabel jLabelMesa14;
    private javax.swing.JLabel jLabelMesa15;
    private javax.swing.JLabel jLabelMesa2;
    private javax.swing.JLabel jLabelMesa3;
    private javax.swing.JLabel jLabelMesa4;
    private javax.swing.JLabel jLabelMesa5;
    private javax.swing.JLabel jLabelMesa6;
    private javax.swing.JLabel jLabelMesa7;
    private javax.swing.JLabel jLabelMesa8;
    private javax.swing.JLabel jLabelMesa9;
    private javax.swing.JLabel jLabelPC;
    private javax.swing.JLabel jLabelPasarelaDerecha;
    private javax.swing.JLabel jLabelPasarelaIzquierda;
    private javax.swing.JLabel jLabelPersonaCola1;
    private javax.swing.JLabel jLabelPersonaCola10;
    private javax.swing.JLabel jLabelPersonaCola11;
    private javax.swing.JLabel jLabelPersonaCola2;
    private javax.swing.JLabel jLabelPersonaCola3;
    private javax.swing.JLabel jLabelPersonaCola4;
    private javax.swing.JLabel jLabelPersonaCola5;
    private javax.swing.JLabel jLabelPersonaCola6;
    private javax.swing.JLabel jLabelPersonaCola7;
    private javax.swing.JLabel jLabelPersonaCola8;
    private javax.swing.JLabel jLabelPersonaCola9;
    private javax.swing.JLabel jLabelPersonaServicio1;
    private javax.swing.JLabel jLabelPersonaServicio10;
    private javax.swing.JLabel jLabelPersonaServicio11;
    private javax.swing.JLabel jLabelPersonaServicio12;
    private javax.swing.JLabel jLabelPersonaServicio13;
    private javax.swing.JLabel jLabelPersonaServicio14;
    private javax.swing.JLabel jLabelPersonaServicio15;
    private javax.swing.JLabel jLabelPersonaServicio16;
    private javax.swing.JLabel jLabelPersonaServicio17;
    private javax.swing.JLabel jLabelPersonaServicio18;
    private javax.swing.JLabel jLabelPersonaServicio19;
    private javax.swing.JLabel jLabelPersonaServicio2;
    private javax.swing.JLabel jLabelPersonaServicio3;
    private javax.swing.JLabel jLabelPersonaServicio4;
    private javax.swing.JLabel jLabelPersonaServicio5;
    private javax.swing.JLabel jLabelPersonaServicio6;
    private javax.swing.JLabel jLabelPersonaServicio7;
    private javax.swing.JLabel jLabelPersonaServicio8;
    private javax.swing.JLabel jLabelPersonaServicio9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCaferiaMesas;
    private javax.swing.JPanel jPanelColaServicio;
    private javax.swing.JPanel jPanelOfinia;
    private javax.swing.JPanel jPanelPasarela;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSlider jSliderVelocidad;
    // End of variables declaration//GEN-END:variables
}
